### ISSUE TITLE
Fix footer too be the same length as nav bar

### ISSUE THREAD

**Issue by karina-klinkeviciute** [karina-klinkeviciute/pyconlt#11]
Footer is now shorter than nav-bar

**Comment by daliusd** [comment]
Is this still a problem?

**Comment by karina-klinkeviciute** [comment]
Yes, it still is. It's more visible on pages with little text. 
![screenshot from 2019-02-04 21-09-24](https://user-images.githubusercontent.com/8834031/52237438-6b916280-28c1-11e9-8389-40ed827461b5.png)
