### ISSUE TITLE
Change color of the bar next to the quote to fit in the color scheme of the website

### ISSUE THREAD

**Issue by karina-klinkeviciute** [karina-klinkeviciute/pyconlt#25]

**Comment by daliusd** [comment]
@karina-klinkeviciute screenshot'as ar kažkas padėtų identifikuoti, ką čia reiktų taisyti.

**Comment by karina-klinkeviciute** [comment]
This red bar next to the quote: 
![screenshot from 2019-02-04 21-14-57](https://user-images.githubusercontent.com/8834031/52237638-00945b80-28c2-11e9-98d4-1182f0e91724.png)
