### ISSUE TITLE
"Signup" end up in the template rendered not as expected

### ISSUE THREAD

**Issue by den4uk** [karina-klinkeviciute/pyconlt#33]
https://github.com/karina-klinkeviciute/pyconlt/blob/c1439767dcc7e9f945e1847b7a5663e09e6514ba/templates/account/signup.html#L6

**Comment by karina-klinkeviciute** [comment]
This project won't be continued, as the webpage for Pycon Lithuania was now moved to another system. If you'd like to use this for your own events, feel free to fork :)
