### ISSUE TITLE
Inform program comittee when there is a new proposal to review

### ISSUE THREAD

**Issue by karina-klinkeviciute** [karina-klinkeviciute/pyconlt#35]
After someone proposes a presentation or workshop, it has to be approved by program committee. For this, it's good to have a system which informs all program committee members about a new proposal.

**Comment by RobertasMurnikovas** [comment]
Can we close this issue now?:)

**Comment by karina-klinkeviciute** [comment]
I think so. If we need it next year, we can raise a new issue.
