### ISSUE TITLE
in sponsors section PetrasZd link is on multiple logos :)

### ISSUE THREAD

**Issue by dz0** [karina-klinkeviciute/pyconlt#67]
Aš nieko prieš Petrą neturiu,  bet https://www.pycon.lt/#sponsors jį link'ina iš Manning,  Vismos, ir pan... :)

**Comment by aidiss** [comment]
Pataisiau.

My bad. Ne ten užbaigiau a elementą.

Šiek tiek užknisa django flatpage editinimas. Gal būtų pusė bėdos, jei išlaikytų formatavimą. Nes dabar po kiekvieno pakeitimo gaunasi bardakas.
