### ISSUE TITLE
JavaScript XSS

### ISSUE THREAD

**Issue by mseimys** [karina-klinkeviciute/pyconlt#82]
It's possible to inject any JavaScript code by editing the title/biography/etc of our talks. E.g. I tried adding `<script>alert('Hi')</script>` to talk title and alert popped. If you must use HTML there, please at least use some tool like [bleach](https://bleach.readthedocs.io/en/latest/clean.html) when generating the HTML.

**Comment by aidiss** [comment]
Thank you very much for letting us know!
@karina-klinkeviciute do we have a solution for this?

**Comment by karina-klinkeviciute** [comment]
Thanks for drawing our attention to this, we will fix it asap.
